version: '3.7'

services:

  wordpress:
    image: wordpress
    depends_on:
      - database
    networks:
      wpnet: {}
    environment:
      - "WORDPRESS_DB_HOST=database"
      - "WORDPRESS_DB_USER=wordpress"
      - "WORDPRESS_DB_PASSWORD=wordpress"
      - "WORDPRESS_DB_NAME=wordpress"
      - "WORDPRESS_DEBUG=1"
    ports:
      - "80:80"
    volumes:
      - "./wordpress:/var/www/html"

  phpmyadmin:
    image: "nazarpc/phpmyadmin"
    depends_on:
      - database
    networks:
      wpnet: {}
    environment:
      - "MYSQL_HOST=database"
      - "UPLOAD_SIZE=2G"
    ports:
      - "8080:80"

  database:
    image: mysql:5.7
    networks:
      wpnet: {}
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_USER=wordpress"
      - "MYSQL_DATABASE=wordpress"
      - "MYSQL_PASSWORD=wordpress"
    ports:
      - "3306:3306"
    volumes:
      - "./database:/var/lib/mysql"

networks:
  wpnet:
